name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod --base-href="https://Yoider98.github.io/https://github.com/Yoider98/eccomerce-Angular/"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/ecommerce-app --no-silent
